### ISSUE TITLE
MOCKUP MENU SECTIONS

### ISSUE THREAD

**Issue by svmalvaez** [sillymatter-mexico/nbc-client#6]
#### Description

New mission here 🚀 

have you seen the sections when you click on the menu button? Well, this section must be laid out with your amazing skills!

#### Tasks
- [ ] Mockup Mis Puntos
- [ ] Mockup Premios
- [ ] Mockup Mecánica
- [ ] Mockup Bases del concurso
- [ ] Mockup Aviso de Provacidad

**Comment by svmalvaez** [comment]
@TrejoYahir this task is in hols while the design team validates the last requirements from client!, but let's move on with the funny part ...the games investigation. 🤓 
See #8
